services:
  dev: 
    volumes:
      - ./app:/usr/src/app
    environment:
      - DEBUG_MODE=True
    build:
      context: app
      target: base
    stop_signal: SIGINT
    ports:
      - '5000:5000'